/**
 * The TextMate grammar, generated from the compiler's own token table.
 *
 * **The direction is the safety property.** This is the argument `AGENTS.md` makes for generating
 * WGSL from GLSL rather than maintaining both: a defect in the generator can only reach the
 * artefact that has a fallback. A grammar that drifts from the lexer still *highlights* — it just
 * highlights the wrong things — so the failure is silent, and silence is what makes it worth a
 * generator rather than a review checklist.
 *
 * `tokens.ts` is the source of truth and nothing else may declare a keyword. This file reads it
 * directly, which Node can do because the package is written in erasable TypeScript for a different
 * reason (its Vite plugin is loaded by the toolchain) — a constraint that happens to pay twice.
 *
 * The cost is a generation step for anybody adding a keyword, and `npm run grammar:check` is what
 * makes forgetting it a failure rather than a slow drift. What would make this wrong is a keyword
 * whose meaning depends on where it appears, because a flat set cannot express one — which is why
 * this language has no contextual keywords, and why the *soft* keywords are highlighted as keywords
 * everywhere they appear. That over-eagerness is stated in `tokens.ts` and is the cheaper half of
 * the trade.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
import {
  ANNOTATIONS,
  KEYWORDS,
  PRIMITIVES,
  PUNCTUATION,
  UNIT_SUFFIXES,
} from '../../compiler/tokens.ts';

const HERE = import.meta.dirname;
const SKELETON = path.join(HERE, 'skeleton.json');
const OUT = path.join(HERE, 'generated', 'driftscript.tmLanguage.json');

/** Escape a token for use inside a regular expression. */
const escape = (text) => text.replace(/[.*+?^${}()|[\]\\/]/g, '\\$&');

/** An alternation of whole words, longest first so a prefix cannot win. */
const words = (list) =>
  [...list]
    .sort((a, b) => b.length - a.length)
    .map(escape)
    .join('|');

/**
 * The keywords that are not type names.
 *
 * Primitives are keywords to the lexer — the grammar and the parser must agree about `f32` — but
 * they read as types to a person, so they get a type scope. Splitting here rather than in
 * `tokens.ts` keeps the compiler's table about lexing and this file about appearance.
 */
const controlKeywords = KEYWORDS.filter((keyword) => !PRIMITIVES.includes(keyword));

const generated = {
  $comment:
    'GENERATED by `npm run grammar` from packages/driftscript/src/compiler/tokens.ts. ' +
    'Never hand-edit: the next generation discards it without saying so. ' +
    '`npm run grammar:check` fails when this file is stale.',
  ...JSON.parse(readFileSync(SKELETON, 'utf8')),
};

delete generated.$comment_skeleton;

generated.repository = {
  ...generated.repository,
  keyword: {
    name: 'keyword.control.driftscript',
    match: `\\b(${words(controlKeywords)})\\b`,
  },
  type: {
    name: 'support.type.primitive.driftscript',
    match: `\\b(${words(PRIMITIVES)})\\b`,
  },
  annotation: {
    name: 'entity.name.function.decorator.driftscript',
    match: `@(${words(ANNOTATIONS)})\\b`,
  },
  number: {
    patterns: [
      {
        /* A unit suffix is part of the literal and is scoped separately, so `250ms` reads as one
           value with a unit rather than as a number beside an identifier. */
        match: `\\b([0-9]+(?:\\.[0-9]+)?)(${words(UNIT_SUFFIXES)})\\b`,
        captures: {
          1: { name: 'constant.numeric.driftscript' },
          2: { name: 'constant.numeric.unit.driftscript' },
        },
      },
      { name: 'constant.numeric.driftscript', match: '\\b[0-9]+(?:\\.[0-9]+)?\\b' },
    ],
  },
  operator: {
    name: 'keyword.operator.driftscript',
    match: `(${words(PUNCTUATION)})`,
  },
};

/* The skeleton's own `$comment` is replaced by the generated warning above, so a reader who opens
   the generated file is told not to edit it before they read anything else. */
generated.$comment =
  'GENERATED by `npm run grammar` from packages/driftscript/src/compiler/tokens.ts. ' +
  'Never hand-edit: the next generation discards it without saying so. ' +
  '`npm run grammar:check` fails when this file is stale.';

const text = `${JSON.stringify(generated, null, 2)}\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    /* Absent counts as stale, and the message below says how to fix it. */
  }
  if (current !== text) {
    console.error(
      'the generated DriftScript grammar is stale.\n' +
        'Run `npm run grammar` and commit the result.\n' +
        'It is generated from packages/driftscript/src/compiler/tokens.ts, which is the only place ' +
        'a keyword may be declared.',
    );
    process.exit(1);
  }
  console.log('ok: the DriftScript grammar matches the token table');
} else {
  writeFileSync(OUT, text);
  console.log(
    `wrote ${path.relative(process.cwd(), OUT)}: ` +
      `${controlKeywords.length} keywords, ${PRIMITIVES.length} types, ` +
      `${ANNOTATIONS.length} annotations, ${PUNCTUATION.length} operators`,
  );
}
